# Generated by Django 6.0.7 on 2026-09-15 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-criado_em'], 'verbose_name': 'pet', 'verbose_name_plural': 'pets'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='pet',
            name='adotado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao',
            field=models.TextField(default='', verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao_necessidades_especiais',
            field=models.TextField(blank=True, verbose_name='descrição das necessidades especiais'),
        ),
        migrations.AddField(
            model_name='pet',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibir o pet em destaque na página inicial.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, upload_to='pets/principais/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='genero',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=15, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade_anos',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade_meses',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='moderado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_moderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='pet',
            name='necessidades_especiais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='ongs.ong'),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=15),
        ),
        migrations.AddField(
            model_name='pet',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(default='Sem raça definida', max_length=80, verbose_name='raça'),
        ),
        migrations.AddField(
            model_name='pet',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_sob_responsabilidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('adotado', 'Adotado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='pendente', max_length=12),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='vermifugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2),
        ),
        migrations.CreateModel(
            name='FotoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/galeria/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pets.pet')),
            ],
            options={
                'verbose_name': 'foto do pet',
                'verbose_name_plural': 'fotos do pet',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
