# Generated by Django 6.1.1 on 2026-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options_remove_pet_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail público para contato'),
        ),
        migrations.AddField(
            model_name='pet',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone público para contato'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('publicado', 'Publicado'), ('adotado', 'Adotado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='pendente', max_length=12),
        ),
    ]
