# Generated by Django 6.1.1 on 2026-09-28 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_email_contato_pet_telefone_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade_estimada_informada',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('coelho', 'Coelho'), ('hamster', 'Hamster'), ('porquinho_da_india', 'Porquinho-da-índia'), ('ave', 'Ave'), ('peixe', 'Peixe'), ('tartaruga', 'Tartaruga / jabuti'), ('furao', 'Furão'), ('chinchila', 'Chinchila'), ('reptil', 'Outro réptil'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade_anos',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Em análise'), ('publicado', 'Publicado'), ('adotado', 'Adotado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='pendente', max_length=12),
        ),
    ]
