# Generated by Django 6.1.1 on 2026-09-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_nascimento_especies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='codigo_demonstracao',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
