"""
Django settings for aumiau project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

from .data_settings import data_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip() or 'django-insecure-l*08z48*#-6mx8@ta_e^_c==p5czp&6k84rh(-r*5qevt95)w0'
DOCUMENT_HASH_KEY = os.environ.get('DOCUMENT_HASH_KEY', '').strip() or SECRET_KEY
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '').strip()
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '').strip()
GOOGLE_REDIRECT_URI = os.environ.get('GOOGLE_REDIRECT_URI', '').strip()

# Links de recuperação são enviados por HTTPS em produção (SMTP é bloqueado no Render Free).
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '').strip() or 'AuMiau <noreply@localhost>'
EMAIL_FROM_NAME = os.environ.get('EMAIL_FROM_NAME', 'AuMiau').strip() or 'AuMiau'
EMAIL_RECOVERY_AVAILABLE = bool(BREVO_API_KEY and os.environ.get('DEFAULT_FROM_EMAIL', '').strip())
EMAIL_BACKEND = 'usuarios.email.BrevoEmailBackend' if EMAIL_RECOVERY_AVAILABLE else 'django.core.mail.backends.dummy.EmailBackend'
PASSWORD_RESET_TIMEOUT = 3600

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('true', '1', 'yes')
if DEBUG and not EMAIL_RECOVERY_AVAILABLE:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_RECOVERY_AVAILABLE = True

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
if os.environ.get('RENDER') == 'true':
    render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
    if render_hostname and render_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_hostname)
    render_origin = f'https://{render_hostname}' if render_hostname else ''
    if render_origin and render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)
if not DEBUG and not os.environ.get('DJANGO_SECRET_KEY', '').strip():
    raise ImproperlyConfigured('Defina DJANGO_SECRET_KEY no ambiente antes de desativar DEBUG.')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
if not DEBUG and os.environ.get('RENDER') == 'true':
    # O TLS termina no proxy do Render; este cabeçalho conserva o esquema original.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'aumiau.apps.AuMiauAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adocoes.apps.AdocoesConfig',
    'pets.apps.PetsConfig',
    'ongs.apps.OngsConfig',
    'usuarios.apps.UsuariosConfig',
    'supervisores.apps.SupervisoresConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'aumiau.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'supervisores.context_processors.acesso_supervisor',
                'usuarios.context_processors.acesso_google',
            ],
        },
    },
]

WSGI_APPLICATION = 'aumiau.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

AUMIAU_DATA_MODE, DATABASES, STORAGES = data_settings(BASE_DIR)
if not DEBUG:
    STORAGES['staticfiles'] = {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
LOGIN_URL = 'usuarios:login'
AUTHENTICATION_BACKENDS = ['usuarios.backends.ContaBackend']
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
TERMOS_VERSAO = '1.1'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
