# Generated by Django 6.0.7 on 2026-09-25 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisores', '0001_criar_grupo_supervisores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('cadastrou', 'Cadastrou'), ('editou', 'Editou'), ('publicou', 'Publicou'), ('rejeitou', 'Rejeitou'), ('adotou', 'Marcou como adotado'), ('arquivou', 'Arquivou'), ('reabriu', 'Reabriu'), ('aprovou', 'Aprovou'), ('ativou', 'Ativou'), ('desativou', 'Desativou'), ('promoveu', 'Promoveu'), ('removeu_acesso', 'Removeu acesso')], max_length=20)),
                ('entidade', models.CharField(max_length=40)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_de_supervisao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de atividade',
                'verbose_name_plural': 'registros de atividades',
                'ordering': ['-criado_em', '-id'],
                'permissions': (('moderar_pet', 'Pode moderar anúncios de pets'), ('moderar_ong', 'Pode moderar cadastros de ONGs'), ('gerenciar_usuarios', 'Pode ativar e inativar usuários')),
            },
        ),
    ]
