# Generated by Django 6.1.1 on 2026-09-30 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0003_chamadoajuda_pet'),
        ('pets', '0005_pet_codigo_demonstracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('pendente', 'Em análise'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('resposta', models.TextField(blank=True, max_length=5000)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adocoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_adocao', to='pets.pet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_adocao', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'solicitação de adoção',
                'verbose_name_plural': 'solicitações de adoção',
                'ordering': ['-criado_em', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('pet', 'usuario'), name='adocao_pendente_pet_usuario')],
            },
        ),
    ]
