# Generated by Django 6.1.1 on 2026-10-01 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_conversas_aprovadas(apps, schema_editor):
    Solicitacao = apps.get_model('adocoes', 'SolicitacaoAdocao')
    Conversa = apps.get_model('adocoes', 'ConversaAdocao')
    banco = schema_editor.connection.alias
    pedidos = Solicitacao.objects.using(banco).filter(status='aprovada').select_related('pet__ong')
    for pedido in pedidos.iterator(chunk_size=500):
        pet = pedido.pet
        anunciante_id = (
            pet.ong.responsavel_id if pet.ong_id and pet.ong.responsavel_id else
            pet.responsavel_id or pet.criado_por_id
        )
        if anunciante_id and anunciante_id != pedido.usuario_id:
            Conversa.objects.using(banco).get_or_create(
                solicitacao_id=pedido.pk, defaults={'anunciante_id': anunciante_id},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0004_solicitacaoadocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_lido_adotante_id', models.PositiveBigIntegerField(default=0)),
                ('ultimo_lido_anunciante_id', models.PositiveBigIntegerField(default=0)),
                ('anunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_como_anunciante', to=settings.AUTH_USER_MODEL, verbose_name='anunciante')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversa_chat', to='adocoes.solicitacaoadocao', verbose_name='solicitação de adoção')),
            ],
            options={
                'verbose_name': 'conversa de adoção',
                'verbose_name_plural': 'conversas de adoção',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000)),
                ('cliente_id', models.UUIDField(verbose_name='identificador do envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_adocao', to=settings.AUTH_USER_MODEL)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='adocoes.conversaadocao')),
            ],
            options={
                'verbose_name': 'mensagem de adoção',
                'verbose_name_plural': 'mensagens de adoção',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['conversa', 'id'], name='adocao_msg_conversa_id')],
                'constraints': [models.UniqueConstraint(fields=('conversa', 'autor', 'cliente_id'), name='adocao_mensagem_envio_unico')],
            },
        ),
        migrations.RunPython(criar_conversas_aprovadas, migrations.RunPython.noop),
    ]
