# Generated by Django 6.1.1 on 2026-09-28 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bloqueio de documento',
                'verbose_name_plural': 'bloqueios de documentos',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='cpf_final',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cpf_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='situacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('banida', 'Banida'), ('excluida', 'Excluída')], default='ativa', max_length=10),
        ),
        migrations.CreateModel(
            name='ContaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_google', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
