# Generated by Django 6.0.7 on 2026-09-25 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preservar_status_ongs_aprovadas(apps, schema_editor):
    Ong = apps.get_model('ongs', 'Ong')
    Ong.objects.filter(aprovada=True).update(status='aprovada')


def restaurar_campo_aprovada(apps, schema_editor):
    Ong = apps.get_model('ongs', 'Ong')
    Ong.objects.update(aprovada=False)
    Ong.objects.filter(status='aprovada').update(aprovada=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='moderado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ongs_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ong',
            name='motivo_rejeicao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('suspensa', 'Suspensa')], default='pendente', max_length=12),
        ),
        migrations.RunPython(
            preservar_status_ongs_aprovadas,
            restaurar_campo_aprovada,
        ),
    ]
