# Generated by Django 6.1.1 on 2026-09-28 13:11

import ongs.cnpj
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0003_ong_responsavel_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[ongs.cnpj.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='ong',
            name='cnpj_confirmado_manualmente',
            field=models.BooleanField(default=False, verbose_name='CNPJ conferido documentalmente pela equipe'),
        ),
        migrations.AddField(
            model_name='ong',
            name='cnpj_consultado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consulta de CNPJ realizada em'),
        ),
        migrations.AddField(
            model_name='ong',
            name='cnpj_situacao',
            field=models.CharField(blank=True, max_length=40, verbose_name='situação cadastral consultada'),
        ),
        migrations.AddField(
            model_name='ong',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='razão social consultada'),
        ),
    ]
