# Generated by Django 6.1.1 on 2026-09-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0004_cnpj_validacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='codigo_demonstracao',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='foto',
            field=models.ImageField(blank=True, upload_to='ongs/%Y/%m/', verbose_name='foto da ONG'),
        ),
    ]
